<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\TreasureChamber.Core\TreasureChamber.Core.csproj" />
    <ProjectReference Include="..\TreasureChamber.Data\TreasureChamber.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MiniExcel" Version="1.41.3" />
    <PackageReference Include="QRCoder" Version="1.8.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
